apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: mcp-server
  title: MCP Server (Golden Path)
  description: Production-ready Model Context Protocol server with tools, resources, and enterprise patterns
  tags:
    - mcp
    - ai
    - typescript
    - python
    - golden-path
spec:
  owner: platform
  type: service

  parameters:
    - title: Component Info
      required:
        - name
        - owner
      properties:
        name:
          title: Name
          type: string
          description: Unique name of the MCP server
          pattern: "^[a-z][a-z0-9-]*$"
          ui:autofocus: true
        owner:
          title: Owner Team
          type: string
          description: Team that owns this server
          ui:field: OwnerPicker
          ui:options:
            catalogFilter:
              kind: Group
        description:
          title: Description
          type: string
          description: What capabilities does this MCP server provide?

    - title: Runtime
      properties:
        language:
          title: Language
          type: string
          enum:
            - typescript
            - python
          enumNames:
            - "TypeScript (Recommended)"
            - "Python (FastMCP)"
          default: typescript
          description: Implementation language
        nodeVersion:
          title: Node.js Version
          type: string
          enum:
            - "22"
            - "20"
            - "18"
          enumNames:
            - "22 (Latest)"
            - "20 (LTS, Recommended)"
            - "18 (LTS)"
          default: "20"
          description: Node.js version (for TypeScript)
        pythonVersion:
          title: Python Version
          type: string
          enum:
            - "3.13"
            - "3.12"
            - "3.11"
          enumNames:
            - "3.13 (Latest)"
            - "3.12 (Recommended)"
            - "3.11 (LTS)"
          default: "3.12"
          description: Python version (for Python)
        packageManager:
          title: Package Manager
          type: string
          enum:
            - npm
            - pnpm
            - yarn
            - uv
            - poetry
          enumNames:
            - "npm"
            - "pnpm (Recommended for TS)"
            - "yarn"
            - "uv (Recommended for Python)"
            - "poetry"
          default: pnpm
          description: Package manager

    - title: MCP Capabilities
      properties:
        enableTools:
          title: Tools
          type: boolean
          default: true
          description: Expose callable functions to the LLM
        enableResources:
          title: Resources
          type: boolean
          default: true
          description: Expose data/context to the LLM
        enablePrompts:
          title: Prompts
          type: boolean
          default: false
          description: Expose reusable prompt templates

    - title: Transport & Deployment
      properties:
        transport:
          title: Transport
          type: string
          enum:
            - stdio
            - http
          enumNames:
            - "STDIO (Local, Recommended)"
            - "HTTP (Remote/Cloud)"
          default: stdio
          description: Communication transport
        deployment:
          title: Deployment Target
          type: string
          enum:
            - local
            - docker
            - lambda
          enumNames:
            - "Local (npx/uvx)"
            - "Docker Container"
            - "AWS Lambda"
          default: local
          description: How the server will be deployed

    - title: Integrations
      properties:
        enableDatabase:
          title: Database Integration
          type: boolean
          default: false
          description: PostgreSQL/SQLite database access
        enableHttp:
          title: HTTP Client
          type: boolean
          default: false
          description: Make external HTTP requests
        enableFileSystem:
          title: File System Access
          type: boolean
          default: false
          description: Read/write local files
        enableGitHub:
          title: GitHub Integration
          type: boolean
          default: false
          description: GitHub API access

    - title: Security
      properties:
        enableAuth:
          title: Authentication
          type: boolean
          default: false
          description: OAuth 2.1 authentication (for HTTP transport)
        inputValidation:
          title: Input Validation
          type: string
          enum:
            - zod
            - pydantic
            - jsonschema
          enumNames:
            - "Zod (TypeScript)"
            - "Pydantic (Python)"
            - "JSON Schema"
          default: zod
          description: Schema validation library

    - title: Repository
      required:
        - repoUrl
      properties:
        repoUrl:
          title: Repository Location
          type: string
          ui:field: RepoUrlPicker
          ui:options:
            allowedHosts:
              - github.com

  steps:
    - id: fetch-skeleton
      name: Fetch Skeleton
      action: fetch:template
      input:
        url: ./skeleton
        values:
          name: ${{ parameters.name }}
          owner: ${{ parameters.owner }}
          description: ${{ parameters.description }}
          language: ${{ parameters.language }}
          nodeVersion: ${{ parameters.nodeVersion }}
          pythonVersion: ${{ parameters.pythonVersion }}
          packageManager: ${{ parameters.packageManager }}
          enableTools: ${{ parameters.enableTools }}
          enableResources: ${{ parameters.enableResources }}
          enablePrompts: ${{ parameters.enablePrompts }}
          transport: ${{ parameters.transport }}
          deployment: ${{ parameters.deployment }}
          enableDatabase: ${{ parameters.enableDatabase }}
          enableHttp: ${{ parameters.enableHttp }}
          enableFileSystem: ${{ parameters.enableFileSystem }}
          enableGitHub: ${{ parameters.enableGitHub }}
          enableAuth: ${{ parameters.enableAuth }}
          inputValidation: ${{ parameters.inputValidation }}

    - id: publish
      name: Publish to GitHub
      action: publish:github
      input:
        allowedHosts:
          - github.com
        repoUrl: ${{ parameters.repoUrl }}
        description: ${{ parameters.description }}
        defaultBranch: main
        protectDefaultBranch: true
        repoVisibility: private

    - id: register
      name: Register Component
      action: catalog:register
      input:
        repoContentsUrl: ${{ steps.publish.output.repoContentsUrl }}
        catalogInfoPath: /catalog-info.yaml

  output:
    links:
      - title: Repository
        url: ${{ steps.publish.output.remoteUrl }}
      - title: Open in Backstage
        icon: catalog
        entityRef: ${{ steps.register.output.entityRef }}
